### ISSUE TITLE
Missing location on globalThis

### ISSUE THREAD

**Issue by travis-r6s** [eidellev/adonis-stardust#13] opened 2022-08-13 11:54 UTC
When running with `inertia/ssr`, `stardust.current` attempts to get the current location from `globalThis.location` - however, `globalThis` does not contain a `location` property.

I was wondering if there was some way to set `globalThis.location` per request in the provider?

**Comment by eidellev** [comment] 2022-08-31 11:19
Hi @thetre97 !
Sorry for the delay. I am looking into it. The problem is that the server does not have the same global `location` as the client has. One of the costs of building isomorphic apps is having to resolve these differences 😄 .

**Comment by eidellev** [comment] 2022-09-02 18:11
this has been fixed in `v3.0.0`
please note the breaking changes

**Closed as completed by eidellev** 2022-09-02 18:11 UTC
Labels: bug
